# Generated by Django 3.2.9 on 2021-11-15 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues_tracker', '0002_contributor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_time']},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['created_time']},
        ),
        migrations.AddField(
            model_name='issue',
            name='project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='issues_tracker.project'),
            preserve_default=False,
        ),
    ]
