# Generated by Django 3.2.9 on 2021-11-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_tracker', '0004_auto_20211117_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('Author', 'Author'), ('Contributor', 'Contributor')], default='Contributor', max_length=11),
        ),
    ]
